ERRAPP.LS      Robot Name ROBOT 16-AUG-23 13:09:26  

1" 16-AUG-23 12:39:18 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
2" 16-AUG-23 01:56:16 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
3" 13-AUG-23 17:36:56 " ARC -121 Weld not performed(Sim mode)             " " WARN                          00000000" 
4" 13-AUG-23 16:17:28 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
5" 13-AUG-23 15:19:38 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
