LOGBOOK.LS     Robot Name ROBOT 16-AUG-23 13:09:26  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Operation        
========================================
FILE 'LAB_WELD_1.TP' is saved          
16-AUG-23 13:09 :26
========================================
FILE 'LABWELD_2.TP' is saved           
16-AUG-23 13:09 :26
========================================
FILE 'IRC_STLABEL.VR' is saved         
16-AUG-23 13:09 :26
========================================
FILE 'IRC_STATUS.VR' is saved          
16-AUG-23 13:09 :26
========================================
FILE 'IRC_MSG.VR' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'IRC_COUNTER.VR' is saved         
16-AUG-23 13:09 :26
========================================
FILE 'IPKDMP.ZIP' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'IOSTATUS.CM' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'HTTPKCL.VR' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'HIST.LS' is saved                
16-AUG-23 13:09 :26
========================================
FILE 'GIGELOG.DG' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'GETDATA.TP' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'GEMDATA.VR' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'FTPLOG.DG' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'FRAMEVAR.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'FLEXUIF.XML' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'FLEXEVENT.DG' is saved           
16-AUG-23 13:09 :26
========================================
FILE 'ETHERNET.DG' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'ERRSYS.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRPWD.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRMOT.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRHIST.LS' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'ERREXT.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRCURR.LS' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'ERRCOMM.LS' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'ERRAPP.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRALL.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'ERRACT.LS' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'EMAIL.DG' is saved               
16-AUG-23 13:09 :26
========================================
FILE 'DIOCFGSV.IO' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_WLDWL.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_WLDST.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_WLDED.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_MOTN0.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI6.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI5.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI4.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI3.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI2.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DF_LOGI1.DF' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DCSVRFY.DG' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'DCSDIFF.DG' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'DCSCHG03.DG' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DCSCHG02.DG' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'DCSCHG01.DG' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'CONSLOG.DG' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'COMSET.VR' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'CELLIO.SV' is saved              
16-AUG-23 13:09 :26
========================================
FILE 'BICSETUP.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'BACKDATE.DT' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'AWTRCSET.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'AWSRCVAR.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'AWSETUP.VR' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'AWSETUP.SV' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'AWSCHED.SV' is saved             
16-AUG-23 13:09 :26
========================================
FILE 'AWE1WP01.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE 'AAVMMAIN.VR' is saved            
16-AUG-23 13:09 :26
========================================
FILE '-BCKEDT-.TP' is saved            
16-AUG-23 13:09 :26
========================================
FILE '-BCKED9-.TP' is saved            
16-AUG-23 13:09 :26
========================================
FILE '-BCKED8-.TP' is saved            
16-AUG-23 13:09 :26
========================================
  WORLD coordinate(G:1)                
16-AUG-23 13:00 :54
========================================
COORD is pressed                       
16-AUG-23 13:00 :54
========================================
  JGFRM coordinate(G:1)                
16-AUG-23 12:59 :36
========================================
COORD is pressed                       
16-AUG-23 12:59 :36
========================================
  JOINT coordinate(G:1)                
16-AUG-23 12:59 :22
========================================
COORD is pressed                       
16-AUG-23 12:59 :22
========================================
   PATH coordinate(G:1)                
16-AUG-23 12:59 :22
========================================
COORD is pressed                       
16-AUG-23 12:59 :22
========================================
   USER coordinate(G:1)                
16-AUG-23 12:59 :12
========================================
COORD is pressed                       
16-AUG-23 12:59 :12
========================================
   TOOL coordinate(G:1)                
16-AUG-23 12:59 :08
========================================
COORD is pressed                       
16-AUG-23 12:59 :08
========================================
  WORLD coordinate(G:1)                
16-AUG-23 12:54 :20
========================================
COORD is pressed                       
16-AUG-23 12:54 :20
========================================
  JGFRM coordinate(G:1)                
16-AUG-23 12:54 :20
========================================
COORD is pressed                       
16-AUG-23 12:54 :20
========================================
  JOINT coordinate(G:1)                
16-AUG-23 12:54 :20
========================================
COORD is pressed                       
16-AUG-23 12:54 :20
========================================
   PATH coordinate(G:1)                
16-AUG-23 12:54 :18
========================================
COORD is pressed                       
16-AUG-23 12:54 :18
========================================
   USER coordinate(G:1)                
16-AUG-23 12:54 :18
========================================
COORD is pressed                       
16-AUG-23 12:54 :18
========================================
   TOOL coordinate(G:1)                
16-AUG-23 12:54 :18
========================================
COORD is pressed                       
16-AUG-23 12:54 :18
========================================
  WORLD coordinate(G:1)                
16-AUG-23 12:54 :18
========================================
COORD is pressed                       
16-AUG-23 12:54 :18
========================================
Override 10%                           
16-AUG-23 12:54 :16
========================================
  JGFRM coordinate(G:1)                
16-AUG-23 12:54 :16
========================================
COORD is pressed                       
16-AUG-23 12:54 :16
========================================
DIAG is pressed                        
16-AUG-23 12:54 :12
========================================
ENTER is pressed                       
16-AUG-23 12:53 :00
========================================
ENTER is pressed                       
16-AUG-23 12:52 :56
========================================
ENTER is pressed                       
16-AUG-23 12:52 :42
========================================
ENTER is pressed                       
16-AUG-23 12:52 :12
========================================
ENTER is pressed                       
16-AUG-23 12:52 :02
========================================
ENTER is pressed                       
16-AUG-23 12:51 :34
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:51 :12
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J  PR[1:Home] 100% FINE\\\                                                 
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:51 :10
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J  PR[1:Home] 100% FINE\\\                                                 
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:51 :10
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:51 :08
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J  PR[1:Home] 100% FINE\\\                                                 
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:51 :08
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:51 :08
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:51 :06
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:51 :06
========================================
ENTER is pressed                       
16-AUG-23 12:51 :06
========================================
ENTER is pressed                       
16-AUG-23 12:51 :02
========================================
ENTER is pressed                       
16-AUG-23 12:51 :00
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:50 :52
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J @P[1] 100% FINE                                                          
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:50 :48
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J @P[1] 100% FINE                                                          
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:50 :48
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:50 :48
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J @P[1] 100% FINE                                                          
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:50 :48
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   9/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:  !Home Position                                                           
   9:J @P[1] 100% FINE                                                          
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:50 :36
========================================
ENTER is pressed                       
16-AUG-23 12:50 :30
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:50 :00
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   6/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :  \\\                                                                      
   7:                                                                           
   8:                                                                           
   9:                                                                           
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:49 :56
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   6/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :  \\\                                                                      
   7:                                                                           
   8:                                                                           
   9:                                                                           
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:49 :54
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   6/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:                                                                           
   9:                                                                           
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:49 :54
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:49 :54
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   6/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:                                                                           
   9:                                                                           
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:49 :54
========================================
F4([CHOICE]) is pressed                
16-AUG-23 12:49 :52
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                   6/31                                         
   1:  !UserFrame_Tool                                                          
   2:  UTOOL_NUM=1                                                              
   3:  UFRAME_NUM=2                                                             
   4:                                                                           
   5:  !Safe Position 2                                                         
   6:J  PR[3:Safe_Position2] 100% FINE                                          
    :                                                                           
   7:                                                                           
   8:                                                                           
   9:                                                                           
  10:                                                                           
  11:                                                                           
  12:                                                                           
  13:                                                                           
  14:                                                                           
  15:                                                                           
  16:                                                                           
  17:                                                                           
  18:                                                                           
  19:                                                                           
                                                                                
                        [CHOICE]                                                
========================================
ENTER is pressed                       
16-AUG-23 12:49 :52
========================================
ENTER is pressed                       
16-AUG-23 12:49 :48
========================================
ENTER is pressed                       
16-AUG-23 12:49 :24
========================================
ENTER is pressed                       
16-AUG-23 12:49 :18
========================================
ENTER is pressed                       
16-AUG-23 12:48 :56
========================================
ENTER is pressed                       
16-AUG-23 12:48 :48
========================================
ENTER is pressed                       
16-AUG-23 12:48 :22
========================================
ENTER is pressed                       
16-AUG-23 12:48 :12
========================================
ENTER is pressed                       
16-AUG-23 12:47 :54
========================================
F5([EDCMD]) is pressed                 
16-AUG-23 12:47 :50
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LABWELD_2         LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
LABWELD_2\\\\\\\\\\\\\\\\\\\\\        i1                                        
                                    1/1                                         
[End]                                                                           
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
Menu changed ''                        
16-AUG-23 12:47 :48
========================================
ENTER is pressed                       
16-AUG-23 12:47 :48
========================================
LabWeld_2 is entered                   
16-AUG-23 12:47 :46
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
                            \T2\        \\\\\\\\\\\JOINT\\\\\\                  
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
                                                                                
 ---  Create Teach Pendant Program  ---                                         
                                                                                
 Program Name:                                                                  
  \                                                                             
                          -- End  --                                            
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Enter program name                                                              
RSR     PNS     MAIN    SUB     TEST                                            
========================================
F2( CREATE ) is pressed                
16-AUG-23 12:47 :40
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
                            \T2\        \\\\\\\\\\\JOINT\\\\\\                  
Select\\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
All  1034016 bytes free           4/7                                           
 No.  Program name       Comment                                                
  1  -BCKEDT-        [                ]                                         
  2  GETDATA      MR [Get PC Data     ]                                         
  3  LAB_WELD_1      [                ]                                         
  4  REQMENU\\\\\\MR [Request PC Menu ]                                         
  5  SENDDATA     MR [Send PC Data    ]                                         
  6  SENDEVNT     MR [Send PC Event   ]                                         
  7  SENDSYSV     MR [Send PC SysVar  ]                                         
                                                                                
                                                                                
                                                                                
                                                                                
[ TYPE ] CREATE DELETE  MONITOR [ATTR ]>                                        
========================================
F4(  YES   ) is pressed                
16-AUG-23 12:47 :38
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_2        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
Select\\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
All  1032552 bytes free           4/8                                           
 No.  Program name       Comment                                                
  1  -BCKEDT-        [                ]                                         
  2  GETDATA      MR [Get PC Data     ]                                         
  3  LAB_WELD_1      [                ]                                         
  4  LAB_WELD_2\\\   [                ]                                         
  5  REQMENU      MR [Request PC Menu ]                                         
  6  SENDDATA     MR [Send PC Data    ]                                         
  7  SENDEVNT     MR [Send PC Event   ]                                         
  8  SENDSYSV     MR [Send PC SysVar  ]                                         
                                                                                
                                                                                
Delete OK ?                                                                     
                          YES     NO                                            
========================================
F3(DELETE  ) is pressed                
16-AUG-23 12:47 :36
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_2        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
Select\\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
All  1032552 bytes free           4/8                                           
 No.  Program name       Comment                                                
  1  -BCKEDT-        [                ]                                         
  2  GETDATA      MR [Get PC Data     ]                                         
  3  LAB_WELD_1      [                ]                                         
  4  LAB_WELD_2\\\   [                ]                                         
  5  REQMENU      MR [Request PC Menu ]                                         
  6  SENDDATA     MR [Send PC Data    ]                                         
  7  SENDEVNT     MR [Send PC Event   ]                                         
  8  SENDSYSV     MR [Send PC SysVar  ]                                         
                                                                                
                                                                                
                                                                                
[ TYPE ] CREATE DELETE  MONITOR [ATTR ]>                                        
========================================
Menu changed 'Select'                  
16-AUG-23 12:47 :32
========================================
SELECT is pressed                      
16-AUG-23 12:47 :32
========================================
Menu changed ''                        
16-AUG-23 12:47 :08
========================================
ENTER is pressed                       
16-AUG-23 12:47 :08
========================================
Menu changed 'Select'                  
16-AUG-23 12:47 :06
========================================
SELECT is pressed                      
16-AUG-23 12:47 :06
========================================
PREV is pressed                        
16-AUG-23 12:47 :04
========================================
PREV is pressed                        
16-AUG-23 12:47 :02
========================================
PREV is pressed                        
16-AUG-23 12:46 :56
========================================
Menu changed ''                        
16-AUG-23 12:46 :54
========================================
EDIT is pressed                        
16-AUG-23 12:46 :54
========================================
SELECT is pressed                      
16-AUG-23 12:46 :52
========================================
F4(  YES   ) is pressed                
16-AUG-23 12:46 :46
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
PROGRAM\COPY\\\\\\\\\\\\\\\\\\       0i1                                        
  ---  Copy Teach Pendant Program  1/1                                          
 From:                                                                          
   LAB_WELD_1                                                                   
 To:                                                                            
   LAB_WELD_2\\\\\\\\\\\\\\\\\\\\\\\\\\                                         
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Copy OK ?                                                                       
                          YES     NO                                            
========================================
LAB_WELD_2 is entered                  
16-AUG-23 12:46 :46
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
PROGRAM\COPY\\\\\\\\\\\\\\\\\\       0i1                                        
  ---  Copy Teach Pendant Program  1/1                                          
 From:                                                                          
   LAB_WELD_1                                                                   
 To:                                                                            
   LAB_WELD_1\\\\\\\\\\\\\\\\\\\\\\\\\\                                         
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Old Value: LAB_WELD_1                                                           
RSR     PNS     MAIN    SUB     TEST                                            
========================================
LAB_WELD_1 is entered                  
16-AUG-23 12:46 :40
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
PROGRAM\COPY\\\\\\\\\\\\\\\\\\       0i1                                        
  ---  Copy Teach Pendant Program  1/1                                          
 From:                                                                          
   LAB_WELD_1                                                                   
 To:                                                                            
   LAB_WELD_1\\\\\\\\\\\\\\\\\\\\\\\\\\                                         
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Old Value: LAB_WELD_1                                                           
RSR     PNS     MAIN    SUB     TEST                                            
========================================
LAB_WELD_1 is entered                  
16-AUG-23 12:46 :40
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
PROGRAM\COPY\\\\\\\\\\\\\\\\\\       0i1                                        
  ---  Copy Teach Pendant Program  1/1                                          
 From:                                                                          
   LAB_WELD_1                                                                   
 To:                                                                            
   LAB_WELD_1\\\\\\\\\\\\\\\\\\\\\\\\\\                                         
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
Old Value: LAB_WELD_1                                                           
RSR     PNS     MAIN    SUB     TEST                                            
========================================
F1(COPY    ) is pressed                
16-AUG-23 12:46 :38
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
Select\\\\\\\\\\\\\\\\\\\\\\\\       0i1                                        
All  1034016 bytes free           3/7                                           
 No.  Program name       Comment                                                
  1  -BCKEDT-        [                ]                                         
  2  GETDATA      MR [Get PC Data     ]                                         
  3  LAB_WELD_1\\\   [                ]                                         
  4  REQMENU      MR [Request PC Menu ]                                         
  5  SENDDATA     MR [Send PC Data    ]                                         
  6  SENDEVNT     MR [Send PC Event   ]                                         
  7  SENDSYSV     MR [Send PC SysVar  ]                                         
                                                                                
                                                                                
                                                                                
                                                                                
COPY    DETAIL  LOAD    SAVE AS PRINT  >                                        
========================================
Menu changed 'Select'                  
16-AUG-23 12:46 :20
========================================
SELECT is pressed                      
16-AUG-23 12:46 :20
========================================
Menu changed ''                        
16-AUG-23 12:46 :16
========================================
EDIT is pressed                        
16-AUG-23 12:46 :16
========================================
Menu changed 'DATA Position Reg'       
16-AUG-23 12:46 :12
========================================
DATA is pressed                        
16-AUG-23 12:46 :12
========================================
SHIFT,F5( RECORD ) is pressed          
16-AUG-23 12:46 :04
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Three Point     4/4                                          
 Frame Number:  2                                                               
                                                                                
   X:    0.0   Y:    0.0   Z:    0.0                                            
   W:    0.0   P:    0.0   R:    0.0                                            
                                                                                
  Comment:          UserFrame2                                                  
  Orient Origin Point:  RECORDED                                                
  X Direction Point:    RECORDED                                                
  Y\Direction\Point:\\\\UNINIT                                                  
                                                                                
                                                                                
                                                                                
[ TYPE ][METHOD] FRAME   MOVE_TO RECORD                                         
========================================
SHIFT,F5( RECORD ) is pressed          
16-AUG-23 12:45 :56
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Three Point     3/4                                          
 Frame Number:  2                                                               
                                                                                
   X:    0.0   Y:    0.0   Z:    0.0                                            
   W:    0.0   P:    0.0   R:    0.0                                            
                                                                                
  Comment:          UserFrame2                                                  
  Orient Origin Point:  RECORDED                                                
  X\Direction\Point:\\\\UNINIT                                                  
  Y Direction Point:    UNINIT                                                  
                                                                                
                                                                                
                                                                                
[ TYPE ][METHOD] FRAME   MOVE_TO RECORD                                         
========================================
SHIFT,F5( RECORD ) is pressed          
16-AUG-23 12:45 :46
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Three Point     2/4                                          
 Frame Number:  2                                                               
                                                                                
   X:    0.0   Y:    0.0   Z:    0.0                                            
   W:    0.0   P:    0.0   R:    0.0                                            
                                                                                
  Comment:          UserFrame2                                                  
  Orient\Origin\Point:\\UNINIT                                                  
  X Direction Point:    UNINIT                                                  
  Y Direction Point:    UNINIT                                                  
                                                                                
                                                                                
                                                                                
[ TYPE ][METHOD] FRAME   MOVE_TO RECORD                                         
========================================
'Three Point' is selected              
16-AUG-23 12:45 :32
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Direct Entry    1/7                                          
 Frame Number:  2                                                               
  1  Comment:   \\\\\\\\\\UserFrame2                                            
  2  X:                     0.000                                               
  3  Y:                     0.000                                               
  4  Z:                     0.000                                               
  5  W:                     0.000                                               
  6  P:                     0.000                                               
  7  R:                     0.000                                               
     Configuration:       N D B, 0, 0, 0                                        
                                                                                
                                                                                
                                                                                
[ TYPE ]|METHOD| FRAME   MOVE_TO RECORD                                         
========================================
F2([METHOD]) is pressed                
16-AUG-23 12:45 :32
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Direct Entry    1/7                                          
 Frame Number:  2                                                               
  1  Comment:   \\\\\\\\\\UserFrame2                                            
  2  X:                     0.000                                               
  3  Y:                     0.000                                               
  4  Z:                     0.000                                               
  5  W:                     0.000                                               
  6  P:                     0.000                                               
  7  R:                     0.000                                               
     Configuration:       N D B, 0, 0, 0                                        
                                                                                
                                                                                
                                                                                
[ TYPE ][METHOD] FRAME   MOVE_TO RECORD                                         
========================================
UserFrame2 is entered                  
16-AUG-23 12:45 :30
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 User Frame        Direct Entry    1/7                                          
 Frame Number:  2                                                               
  1  Comment:   \\\\\\\\\\\\\UFrame2                                            
  2  X:                     0.000                                               
  3  Y:                     0.000                                               
  4  Z:                     0.000                                               
  5  W:                     0.000                                               
  6  P:                     0.000                                               
  7  R:                     0.000                                               
     Configuration:       N D B, 0, 0, 0                                        
                                                                                
                                                                                
Old Value: UFrame2                                                              
   ABCDEF GHIJKL  MNOPQR STUVWX  YZ_@*.                                         
========================================
ENTER is pressed                       
16-AUG-23 12:45 :26
========================================
ENTER is pressed                       
16-AUG-23 12:45 :24
========================================
'User Frame' is selected               
16-AUG-23 12:45 :20
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 Tool Frame      / Three Point    1/10                                          
      X     Y      Z    Comment                                                 
  1\ -84.8     .0  449.8 [MTB500i_G_R  ]                                        
  2    0.0    0.0    0.0 [Eoat2        ]                                        
  3    0.0    0.0    0.0 [Eoat3        ]                                        
  4    0.0    0.0    0.0 [Eoat4        ]                                        
  5    0.0    0.0    0.0 [Eoat5        ]                                        
  6    0.0    0.0    0.0 [Eoat6        ]                                        
  7    0.0    0.0    0.0 [Eoat7        ]                                        
  8    0.0    0.0    0.0 [Eoat8        ]                                        
  9    0.0    0.0    0.0 [Eoat9        ]                                        
 10    0.0    0.0    0.0 [Eoat10       ]                                        
                                                                                
[ TYPE ] DETAIL |OTHER |  CLEAR  SETIND                                         
========================================
F3([OTHER ]) is pressed                
16-AUG-23 12:45 :18
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 Tool Frame      / Three Point    1/10                                          
      X     Y      Z    Comment                                                 
  1\ -84.8     .0  449.8 [MTB500i_G_R  ]                                        
  2    0.0    0.0    0.0 [Eoat2        ]                                        
  3    0.0    0.0    0.0 [Eoat3        ]                                        
  4    0.0    0.0    0.0 [Eoat4        ]                                        
  5    0.0    0.0    0.0 [Eoat5        ]                                        
  6    0.0    0.0    0.0 [Eoat6        ]                                        
  7    0.0    0.0    0.0 [Eoat7        ]                                        
  8    0.0    0.0    0.0 [Eoat8        ]                                        
  9    0.0    0.0    0.0 [Eoat9        ]                                        
 10    0.0    0.0    0.0 [Eoat10       ]                                        
                                                                                
[ TYPE ] DETAIL [OTHER ]  CLEAR  SETIND                                         
========================================
F3([OTHER ]) is pressed                
16-AUG-23 12:45 :18
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 Tool Frame      / Three Point    1/10                                          
      X     Y      Z    Comment                                                 
  1\ -84.8     .0  449.8 [MTB500i_G_R  ]                                        
  2    0.0    0.0    0.0 [Eoat2        ]                                        
  3    0.0    0.0    0.0 [Eoat3        ]                                        
  4    0.0    0.0    0.0 [Eoat4        ]                                        
  5    0.0    0.0    0.0 [Eoat5        ]                                        
  6    0.0    0.0    0.0 [Eoat6        ]                                        
  7    0.0    0.0    0.0 [Eoat7        ]                                        
  8    0.0    0.0    0.0 [Eoat8        ]                                        
  9    0.0    0.0    0.0 [Eoat9        ]                                        
 10    0.0    0.0    0.0 [Eoat10       ]                                        
                                                                                
| TYPE | DETAIL [OTHER ]  CLEAR  SETIND                                         
========================================
F1([ TYPE ]) is pressed                
16-AUG-23 12:45 :14
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
SETUP\Frames\\\\\\\\\\\\\\\\\\       0i1                                        
 Tool Frame      / Three Point    1/10                                          
      X     Y      Z    Comment                                                 
  1\ -84.8     .0  449.8 [MTB500i_G_R  ]                                        
  2    0.0    0.0    0.0 [Eoat2        ]                                        
  3    0.0    0.0    0.0 [Eoat3        ]                                        
  4    0.0    0.0    0.0 [Eoat4        ]                                        
  5    0.0    0.0    0.0 [Eoat5        ]                                        
  6    0.0    0.0    0.0 [Eoat6        ]                                        
  7    0.0    0.0    0.0 [Eoat7        ]                                        
  8    0.0    0.0    0.0 [Eoat8        ]                                        
  9    0.0    0.0    0.0 [Eoat9        ]                                        
 10    0.0    0.0    0.0 [Eoat10       ]                                        
Active TOOL $MNUTOOLNUM[1] = 1                                                  
[ TYPE ] DETAIL [OTHER ]  CLEAR  SETIND                                         
========================================
Menu changed 'SETUP Frames'            
16-AUG-23 12:45 :08
========================================
'Frames' is selected in 'SETUP' MENU fl
yout                                   
16-AUG-23 12:45 :08
========================================
ENTER is pressed                       
16-AUG-23 12:45 :08
========================================
Safe_Position2 is entered              
16-AUG-23 12:44 :50
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
                                   3/100                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=R                                                      
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
PR[  8:                ]=*                                                      
PR[  9:                ]=*                                                      
PR[ 10:                ]=*                                                      
PR[ 11:                ]=*                                                      
Old Value:                                                                      
   ABCDEF GHIJKL  MNOPQR STUVWX  YZ_@*.                                         
========================================
F4(  DONE  ) is pressed                
16-AUG-23 12:44 :34
--Screen image--------------------------
TPIF-234 Offset may be applied to PR[3],                                        
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
 PR[3] UF:F  UT:F                                                               
 J1 \\\\90.000 deg  J4      0.000 deg                                           
 J2      0.000 deg  J5      0.000 deg                                           
 J3      0.000 deg  J6      0.000 deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=R\\\\\\\\\\\\\\                                        
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
Enter value                                                                     
                          DONE  [REPRE]                                         
========================================
'Joint' is selected                    
16-AUG-23 12:44 :28
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
 PR[3] UF:F  UT:F        CONF:NUT 000                                           
 X \\-915.904   mm  W       .000  deg                                           
 Y   -352.688   mm  P    -54.000  deg                                           
 Z    595.199   mm  R   -179.899  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=R\\\\\\\\\\\\\\                                        
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
Enter value                                                                     
                  CONF    DONE  |REPRE|                                         
========================================
F5([REPRE] ) is pressed                
16-AUG-23 12:44 :28
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
 PR[3] UF:F  UT:F        CONF:NUT 000                                           
 X \\-915.904   mm  W       .000  deg                                           
 Y   -352.688   mm  P    -54.000  deg                                           
 Z    595.199   mm  R   -179.899  deg                                           
Position\Detail\\\\\\\\\\\\\\\\\\\\\\\\\                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=R\\\\\\\\\\\\\\                                        
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
Enter value                                                                     
                  CONF    DONE  [REPRE]                                         
========================================
F4(POSITION) is pressed                
16-AUG-23 12:44 :26
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
                                   3/100                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=R\\\\\\\\\\\\\\                                        
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
PR[  8:                ]=*                                                      
PR[  9:                ]=*                                                      
PR[ 10:                ]=*                                                      
PR[ 11:                ]=*                                                      
Position has been recorded to PR[3].                                            
[ TYPE ] MOVE_TO RECORD POSITION  CLEAR                                         
========================================
SHIFT,F3( RECORD ) is pressed          
16-AUG-23 12:44 :24
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Position\Reg\\\\\\\\\\\\\       0i1                                        
                                   3/100                                        
PR[  1:Home            ]=R                                                      
PR[  2:Safe_Position   ]=R                                                      
PR[  3:                ]=*\\\\\\\\\\\\\\                                        
PR[  4:                ]=*                                                      
PR[  5:                ]=*                                                      
PR[  6:                ]=*                                                      
PR[  7:                ]=*                                                      
PR[  8:                ]=*                                                      
PR[  9:                ]=*                                                      
PR[ 10:                ]=*                                                      
PR[ 11:                ]=*                                                      
                                                                                
[ TYPE ] MOVE_TO RECORD POSITION  CLEAR                                         
========================================
Menu changed 'DATA Position Reg'       
16-AUG-23 12:44 :16
========================================
'Position Reg' is selected             
16-AUG-23 12:44 :16
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Weld\Procedure\ 1 \\\\\\\       0 1                                        
                                   1/2                                          
 +  Procedure       1 [                ]                                        
   +  Schedules                                                                 
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
| TYPE | DETAIL [ CMND ][ VIEW ]  HELP                                          
========================================
F1([ TYPE ]) is pressed                
16-AUG-23 12:44 :16
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 0    \T2\ ABORTED\\\\\\\\\\\JOINT\\\\\\                  
DATA\Weld\Procedure\ 1 \\\\\\\       0 1                                        
                                   1/2                                          
 +  Procedure       1 [                ]                                        
   +  Schedules                                                                 
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
[ TYPE ] DETAIL [ CMND ][ VIEW ]  HELP                                          
========================================
Menu changed 'DATA Weld Procedure'     
16-AUG-23 12:44 :14
========================================
DATA is pressed                        
16-AUG-23 12:44 :14
========================================
Menu changed 'Select'                  
16-AUG-23 12:44 :10
========================================
SELECT is pressed                      
16-AUG-23 12:44 :10
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:43 :48
========================================
Override 100%                          
16-AUG-23 12:43 :42
========================================
Override 3%                            
16-AUG-23 12:43 :42
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:43 :42
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:43 :42
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
16-AUG-23 12:43 :42
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
16-AUG-23 12:43 :42
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
16-AUG-23 12:43 :42
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:43 :42
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
16-AUG-23 12:43 :42
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
16-AUG-23 12:43 :42
========================================
Focus changed to ''                    
16-AUG-23 12:43 :42
========================================
FILE 'T_ARCWELD.LS' is saved           
16-AUG-23 12:43 :40
========================================
FILE 'TEMPLATES.LS' is saved           
16-AUG-23 12:43 :40
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:39 :22
========================================
Override 100%                          
16-AUG-23 12:39 :22
========================================
FILE 'AWE1WP01.VR' is saved            
16-AUG-23 12:39 :20
========================================
Menu changed 'UTILITIES Hints'         
16-AUG-23 12:39 :18
========================================
Override 10%                           
16-AUG-23 12:39 :18
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
16-AUG-23 12:39 :18
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 12:39 :18
========================================
Cold start                             
16-AUG-23 12:39 :08
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 01:58 :06
========================================
FILE 'ZDLOG.DG' is saved               
16-AUG-23 01:58 :06
========================================
FILE 'WVSETUP.SV' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'WVSCHED.SV' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'VTRNDIAG.LS' is saved            
16-AUG-23 01:58 :06
========================================
FILE 'VIMGDIAG.ZIP' is saved           
16-AUG-23 01:58 :06
========================================
FILE 'VDEVDIAG.DAT' is saved           
16-AUG-23 01:58 :06
========================================
FILE 'VCMRINIT.VR' is saved            
16-AUG-23 01:58 :06
========================================
FILE 'VARCHG.XML' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'UPDTLOG.LS' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'UPDATES.DAT' is saved            
16-AUG-23 01:58 :06
========================================
FILE 'TPEINS.XML' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'TPACCN.DG' is saved              
16-AUG-23 01:58 :06
========================================
FILE 'SYSVARS.SV' is saved             
16-AUG-23 01:58 :06
========================================
FILE 'SYSUIF.SV' is saved              
16-AUG-23 01:58 :06
========================================
FILE 'SYSSERVO.SV' is saved            
16-AUG-23 01:58 :06
========================================
FILE 'SYSPASS.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'SYSMAST.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'SYSMACRO.SV' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'SYSHOST.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'SYSFSAC.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'SYSFRAME.SV' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'SWIUPDT.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'SUMMARY.DG' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'STRREG.VR' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'SHADOW.DG' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'SENDSYSV.TP' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'SENDEVNT.TP' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'SENDDATA.TP' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'SECLOG.DG' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'REQMENU.TP' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'RCMSGLIB.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'RCMERR.DG' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'RCMCFG.XML' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'PSRBWLD.CM' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'POSREG.VR' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ORDERFIL.DAT' is saved           
16-AUG-23 01:58 :04
========================================
FILE 'NUMREG.VR' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'NOTIFY.DG' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'MTPARAM.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'MIXLOGIC.SV' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'MEMCHECK.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'LR2D.DT' is saved                
16-AUG-23 01:58 :04
========================================
FILE 'LOGBOOK.LS' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'LAB_WELD_1.TP' is saved          
16-AUG-23 01:58 :04
========================================
FILE 'IRC_STLABEL.VR' is saved         
16-AUG-23 01:58 :04
========================================
FILE 'IRC_STATUS.VR' is saved          
16-AUG-23 01:58 :04
========================================
FILE 'IRC_MSG.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'IRC_COUNTER.VR' is saved         
16-AUG-23 01:58 :04
========================================
FILE 'IPKDMP.ZIP' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'IOSTATUS.CM' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'HTTPKCL.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'HIST.LS' is saved                
16-AUG-23 01:58 :04
========================================
FILE 'GIGELOG.DG' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'GETDATA.TP' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'GEMDATA.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'FTPLOG.DG' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'FRAMEVAR.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'FLEXUIF.XML' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'FLEXEVENT.DG' is saved           
16-AUG-23 01:58 :04
========================================
FILE 'ETHERNET.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'ERRSYS.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRPWD.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRMOT.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRHIST.LS' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'ERREXT.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRCURR.LS' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'ERRCOMM.LS' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'ERRAPP.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRALL.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'ERRACT.LS' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'EMAIL.DG' is saved               
16-AUG-23 01:58 :04
========================================
FILE 'DIOCFGSV.IO' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_WLDWL.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_WLDST.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_WLDED.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_MOTN0.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI6.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI5.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI4.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI3.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI2.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DF_LOGI1.DF' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DCSVRFY.DG' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'DCSDIFF.DG' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'DCSCHG03.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DCSCHG02.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'DCSCHG01.DG' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'CONSLOG.DG' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'COMSET.VR' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'CELLIO.SV' is saved              
16-AUG-23 01:58 :04
========================================
FILE 'BICSETUP.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'BACKDATE.DT' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'AWTRCSET.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'AWSRCVAR.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'AWSETUP.VR' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'AWSETUP.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'AWSCHED.SV' is saved             
16-AUG-23 01:58 :04
========================================
FILE 'AWE1WP01.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE 'AAVMMAIN.VR' is saved            
16-AUG-23 01:58 :04
========================================
FILE '-BCKEDT-.TP' is saved            
16-AUG-23 01:58 :04
========================================
FILE '-BCKED9-.TP' is saved            
16-AUG-23 01:58 :04
========================================
FILE '-BCKED8-.TP' is saved            
16-AUG-23 01:58 :04
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 01:56 :22
========================================
Override 100%                          
16-AUG-23 01:56 :22
========================================
FILE 'AWE1WP01.VR' is saved            
16-AUG-23 01:56 :18
========================================
Menu changed 'UTILITIES Hints'         
16-AUG-23 01:56 :16
========================================
Override 10%                           
16-AUG-23 01:56 :16
========================================
  JOINT coordinate(G:1)                
16-AUG-23 01:56 :16
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
16-AUG-23 01:56 :14
========================================
R E S E T                              
                                       
                              00000000 
16-AUG-23 01:56 :14
========================================
Cold start                             
16-AUG-23 01:55 :56
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:37 :46
========================================
FILE 'ZDLOG.DG' is saved               
13-AUG-23 17:37 :46
========================================
FILE 'WVSETUP.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'WVSCHED.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'VTRNDIAG.LS' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'VIMGDIAG.ZIP' is saved           
13-AUG-23 17:37 :46
========================================
FILE 'VDEVDIAG.DAT' is saved           
13-AUG-23 17:37 :46
========================================
FILE 'VCMRINIT.VR' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'VARCHG.XML' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'STRREG.VR' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'SECLOG.DG' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'RCMSGLIB.DG' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'RCMERR.DG' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'RCMCFG.XML' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'POSREG.VR' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-23 17:37 :46
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-23 17:37 :46
========================================
FILE 'MTPARAM.VR' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'LR2D.DT' is saved                
13-AUG-23 17:37 :46
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'LAB_WELD_1.TP' is saved          
13-AUG-23 17:37 :46
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-23 17:37 :46
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-23 17:37 :46
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-23 17:37 :46
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-23 17:37 :46
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'HIST.LS' is saved                
13-AUG-23 17:37 :46
========================================
FILE 'GIGELOG.DG' is saved             
13-AUG-23 17:37 :46
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'FLEXUIF.XML' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'FLEXEVENT.DG' is saved           
13-AUG-23 17:37 :44
========================================
FILE 'ETHERNET.DG' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'ERRSYS.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRPWD.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRMOT.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRHIST.LS' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'ERREXT.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRCURR.LS' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'ERRCOMM.LS' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'ERRAPP.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'ERRACT.LS' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'EMAIL.DG' is saved               
13-AUG-23 17:37 :44
========================================
FILE 'DIOCFGSV.IO' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_WLDWL.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_WLDST.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_WLDED.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_MOTN0.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI6.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI5.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI4.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI3.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI2.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DF_LOGI1.DF' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DCSVRFY.DG' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'DCSDIFF.DG' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'DCSCHG03.DG' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DCSCHG02.DG' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'DCSCHG01.DG' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'CONSLOG.DG' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'COMSET.VR' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'CELLIO.SV' is saved              
13-AUG-23 17:37 :44
========================================
FILE 'BICSETUP.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'BACKDATE.DT' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'AWTRCSET.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'AWSRCVAR.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'AWSETUP.VR' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'AWSETUP.SV' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'AWSCHED.SV' is saved             
13-AUG-23 17:37 :44
========================================
FILE 'AWE1WP01.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE 'AAVMMAIN.VR' is saved            
13-AUG-23 17:37 :44
========================================
FILE '-BCKEDT-.TP' is saved            
13-AUG-23 17:37 :44
========================================
FILE '-BCKED9-.TP' is saved            
13-AUG-23 17:37 :44
========================================
FILE '-BCKED8-.TP' is saved            
13-AUG-23 17:37 :44
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:37 :40
========================================
FILE 'ZDLOG.DG' is saved               
13-AUG-23 17:37 :40
========================================
FILE 'WVSETUP.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'WVSCHED.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'VTRNDIAG.LS' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'VIMGDIAG.ZIP' is saved           
13-AUG-23 17:37 :40
========================================
FILE 'VDEVDIAG.DAT' is saved           
13-AUG-23 17:37 :40
========================================
FILE 'VCMRINIT.VR' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'VARCHG.XML' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'STRREG.VR' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'SECLOG.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'RCMSGLIB.DG' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'RCMERR.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'RCMCFG.XML' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'POSREG.VR' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-23 17:37 :40
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'MTPARAM.VR' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'LR2D.DT' is saved                
13-AUG-23 17:37 :40
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'LAB_WELD_1.TP' is saved          
13-AUG-23 17:37 :40
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-23 17:37 :40
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-23 17:37 :40
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-23 17:37 :40
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'HIST.LS' is saved                
13-AUG-23 17:37 :40
========================================
FILE 'GIGELOG.DG' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'FLEXUIF.XML' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'FLEXEVENT.DG' is saved           
13-AUG-23 17:37 :40
========================================
FILE 'ETHERNET.DG' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'ERRSYS.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRPWD.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRMOT.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRHIST.LS' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'ERREXT.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRCURR.LS' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'ERRCOMM.LS' is saved             
13-AUG-23 17:37 :40
========================================
FILE 'ERRAPP.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRALL.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'ERRACT.LS' is saved              
13-AUG-23 17:37 :40
========================================
FILE 'EMAIL.DG' is saved               
13-AUG-23 17:37 :40
========================================
FILE 'DIOCFGSV.IO' is saved            
13-AUG-23 17:37 :40
========================================
FILE 'DF_WLDWL.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_WLDST.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_WLDED.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_MOTN0.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI6.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI5.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI4.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI3.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI2.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DF_LOGI1.DF' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DCSVRFY.DG' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'DCSDIFF.DG' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'DCSCHG03.DG' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DCSCHG02.DG' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'DCSCHG01.DG' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'CONSLOG.DG' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'COMSET.VR' is saved              
13-AUG-23 17:37 :38
========================================
FILE 'CELLIO.SV' is saved              
13-AUG-23 17:37 :38
========================================
FILE 'BICSETUP.VR' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'BACKDATE.DT' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'AWTRCSET.VR' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'AWSRCVAR.VR' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'AWSETUP.VR' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'AWSETUP.SV' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'AWSCHED.SV' is saved             
13-AUG-23 17:37 :38
========================================
FILE 'AWE1WP01.VR' is saved            
13-AUG-23 17:37 :38
========================================
FILE 'AAVMMAIN.VR' is saved            
13-AUG-23 17:37 :38
========================================
FILE '-BCKEDT-.TP' is saved            
13-AUG-23 17:37 :38
========================================
FILE '-BCKED9-.TP' is saved            
13-AUG-23 17:37 :38
========================================
FILE '-BCKED8-.TP' is saved            
13-AUG-23 17:37 :38
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:36 :52
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:36 :52
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:36 :52
========================================
Override 100%                          
13-AUG-23 17:36 :52
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
13-AUG-23 17:36 :52
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
13-AUG-23 17:36 :50
========================================
Single step OFF                        
13-AUG-23 17:36 :36
========================================
STEP is pressed                        
13-AUG-23 17:36 :36
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :26
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
13-AUG-23 17:36 :24
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
________________________________
|The cursor is on a different  |
|line from where the program   |
|PAUSED [17].                  |
|Are you sure you want to run  |
|from this line ?              |
|                              |
|       YES           NO       |
|______________________________|
[ INST ]                        [EDCMD]>                                        
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:36 :22
========================================
Single step ON                         
13-AUG-23 17:36 :20
========================================
SHIFT,STEP is pressed                  
13-AUG-23 17:36 :20
========================================
Single step OFF                        
13-AUG-23 17:36 :14
========================================
STEP is pressed                        
13-AUG-23 17:36 :14
========================================
PREV is pressed                        
13-AUG-23 17:35 :56
========================================
F3(POSID) is pressed                   
13-AUG-23 17:35 :50
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
LAB_WELD_1\\\\\\\\\\\\\\\\\\\\        i1                                        
                       PAUSED     23/26                                         
   7:                                                                           
   8:  !Home_Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:  !Weld Start Safe Pos                                                     
  12:J  P[2] 100% FINE                                                          
  13:                                                                           
  14:  !WELD START                                                              
  15:L  P[1] 100.0inch/min FINE                                                 
    :  Weld Start[1,1]                                                          
  16:                                                                           
  17:  !WELD END                                                                
  18:L  P[3] WELD_SPEED FINE                                                    
    :  Weld End[1,1]                                                            
  19:                                                                           
  20:  !Weld End Safe Pos                                                       
  21:J @P[4] 100% FINE                                                          
  22:                                                                           
\\23:                                                                           
  24:                                                                           
Paste before this line ?                                                        
        LOGIC   POSID   POSITIONCANCEL >                                        
========================================
F5(PASTE) is pressed                   
13-AUG-23 17:35 :48
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
LAB_WELD_1\\\\\\\\\\\\\\\\\\\\        i1                                        
                       PAUSED     23/26                                         
   7:                                                                           
   8:  !Home_Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:  !Weld Start Safe Pos                                                     
  12:J  P[2] 100% FINE                                                          
  13:                                                                           
  14:  !WELD START                                                              
  15:L  P[1] 100.0inch/min FINE                                                 
    :  Weld Start[1,1]                                                          
  16:                                                                           
  17:  !WELD END                                                                
  18:L  P[3] WELD_SPEED FINE                                                    
    :  Weld End[1,1]                                                            
  19:                                                                           
  20:  !Weld End Safe Pos                                                       
  21:J @P[4] 100% FINE                                                          
  22:                                                                           
\\23:                                                                           
  24:                                                                           
                                                                                
        SELECT                  PASTE                                           
========================================
F2(COPY) is pressed                    
13-AUG-23 17:35 :42
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
LAB_WELD_1\\\\\\\\\\\\\\\\\\\\        i1                                        
                       PAUSED      9/26                                         
   7:                                                                           
\\\8:  !Home_Position                                                           
\\\9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:  !Weld Start Safe Pos                                                     
  12:J  P[2] 100% FINE                                                          
  13:                                                                           
  14:  !WELD START                                                              
  15:L  P[1] 100.0inch/min FINE                                                 
    :  Weld Start[1,1]                                                          
  16:                                                                           
  17:  !WELD END                                                                
  18:L  P[3] WELD_SPEED FINE                                                    
    :  Weld End[1,1]                                                            
  19:                                                                           
  20:  !Weld End Safe Pos                                                       
  21:J @P[4] 100% FINE                                                          
  22:                                                                           
  23:                                                                           
  24:                                                                           
                                                                                
        COPY    CUT             PASTE                                           
========================================
F2(SELECT) is pressed                  
13-AUG-23 17:35 :40
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
LAB_WELD_1\\\\\\\\\\\\\\\\\\\\        i1                                        
                       PAUSED      8/26                                         
   7:                                                                           
\\\8:  !Home_Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:  !Weld Start Safe Pos                                                     
  12:J  P[2] 100% FINE                                                          
  13:                                                                           
  14:  !WELD START                                                              
  15:L  P[1] 100.0inch/min FINE                                                 
    :  Weld Start[1,1]                                                          
  16:                                                                           
  17:  !WELD END                                                                
  18:L  P[3] WELD_SPEED FINE                                                    
    :  Weld End[1,1]                                                            
  19:                                                                           
  20:  !Weld End Safe Pos                                                       
  21:J @P[4] 100% FINE                                                          
  22:                                                                           
  23:                                                                           
  24:                                                                           
Select lines                                                                    
        SELECT                  PASTE                                           
========================================
F5([EDCMD]) is pressed                 
13-AUG-23 17:35 :36
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 17   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
LAB_WELD_1\\\\\\\\\\\\\\\\\\\\        i1                                        
                       PAUSED      8/26                                         
   7:                                                                           
\\\8:  !Home_Position                                                           
   9:J  PR[1:Home] 100% FINE                                                    
  10:                                                                           
  11:  !Weld Start Safe Pos                                                     
  12:J  P[2] 100% FINE                                                          
  13:                                                                           
  14:  !WELD START                                                              
  15:L  P[1] 100.0inch/min FINE                                                 
    :  Weld Start[1,1]                                                          
  16:                                                                           
  17:  !WELD END                                                                
  18:L  P[3] WELD_SPEED FINE                                                    
    :  Weld End[1,1]                                                            
  19:                                                                           
  20:  !Weld End Safe Pos                                                       
  21:J @P[4] 100% FINE                                                          
  22:                                                                           
  23:                                                                           
  24:                                                                           
                                                                                
[ INST ]                        [EDCMD]>                                        
========================================
   TOOL coordinate(G:1)                
13-AUG-23 17:35 :02
========================================
COORD is pressed                       
13-AUG-23 17:35 :02
========================================
ENTER is pressed                       
13-AUG-23 17:34 :58
========================================
ENTER is pressed                       
13-AUG-23 17:34 :08
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :26
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :12
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :10
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :10
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :06
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :06
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
13-AUG-23 17:33 :04
--Screen image--------------------------
TPIF-106 Program is already running                                             
LAB_WELD_1        LINE 15   \T2\ PAUSED \\\\\\\\\\\WORLD\\\\\\                  
________________________________
|The cursor is on a different  |
|line from where the program   |
|PAUSED [15].                  |
|Are you sure you want to run  |
|from this line ?              |
|                              |
|       YES           NO       |
|______________________________|
POINT   WELD_ST WELD_PT WELDEND TOUCHUP>                                        
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:33 :04
========================================
  WORLD coordinate(G:1)                
13-AUG-23 17:31 :40
========================================
COORD is pressed                       
13-AUG-23 17:31 :40
========================================
  JGFRM coordinate(G:1)                
13-AUG-23 17:31 :40
========================================
COORD is pressed                       
13-AUG-23 17:31 :40
========================================
  JOINT coordinate(G:1)                
13-AUG-23 17:31 :38
========================================
COORD is pressed                       
13-AUG-23 17:31 :38
========================================
   PATH coordinate(G:1)                
13-AUG-23 17:31 :36
========================================
COORD is pressed                       
13-AUG-23 17:31 :36
========================================
Override 10%                           
13-AUG-23 17:31 :36
========================================
   USER coordinate(G:1)                
13-AUG-23 17:31 :36
========================================
COORD is pressed                       
13-AUG-23 17:31 :36
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:31 :10
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:31 :08
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:31 :06
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:31 :00
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :58
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :58
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :54
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :52
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :52
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :52
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :52
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :50
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :50
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :50
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :50
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :44
========================================
'   YES' is selected in ' The cursor i
s on a different' window              
13-AUG-23 17:30 :42
--Screen image--------------------------
                                                                                
LAB_WELD_1        LINE 15   \T2\ PAUSED \\\\\\\\\\\\TOOL\\\\\\                  
________________________________
|The cursor is on a different  |
|line from where the program   |
|PAUSED [15].                  |
|Are you sure you want to run  |
|from this line ?              |
|                              |
|       YES           NO       |
|______________________________|
POINT   WELD_ST WELD_PT WELDEND TOUCHUP>                                        
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :40
========================================
Single step ON                         
13-AUG-23 17:30 :38
========================================
STEP is pressed                        
13-AUG-23 17:30 :38
========================================
Override 100%                          
13-AUG-23 17:30 :36
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:30 :36
========================================
Override 3%                            
13-AUG-23 17:30 :36
========================================
Override 100%                          
13-AUG-23 17:30 :36
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:30 :36
========================================
SYST-039 Operation mode T2 Selected    
                                       
                                       
SERVO                         00110110 
13-AUG-23 17:30 :36
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
13-AUG-23 17:30 :36
========================================
SYST-045 TP enabled in AUTO mode       
                                       
                                       
STOP.G                        00100110 
13-AUG-23 17:30 :36
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:30 :36
========================================
SYST-040 Operation mode AUTO Selected  
                                       
                                       
SERVO                         00110110 
13-AUG-23 17:30 :36
========================================
SYST-043 TP disabled in T1/T2 mode     
                                       
                                       
STOP.L                        00000110 
13-AUG-23 17:30 :36
========================================
SYST-042 DEADMAN defeated              
                                       
                                       
SERVO                         00110110 
13-AUG-23 17:30 :36
========================================
Single step OFF                        
13-AUG-23 17:30 :32
========================================
STEP is pressed                        
13-AUG-23 17:30 :32
========================================
SHIFT,FWD is pressed                   
13-AUG-23 17:30 :20
========================================
   TOOL coordinate(G:1)                
13-AUG-23 17:29 :46
========================================
COORD is pressed                       
13-AUG-23 17:29 :46
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:28 :14
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:28 :08
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:28 :06
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:28 :00
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:27 :52
========================================
SHIFT,-X(J1) is pressed                
13-AUG-23 17:27 :44
========================================
SHIFT,-X(J1) is pressed                
13-AUG-23 17:27 :34
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:27 :28
========================================
+% is pressed                          
13-AUG-23 17:27 :24
========================================
+% is pressed                          
13-AUG-23 17:27 :24
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:27 :18
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:27 :12
========================================
-% is pressed                          
13-AUG-23 17:27 :08
========================================
-% is pressed                          
13-AUG-23 17:27 :08
========================================
-% is pressed                          
13-AUG-23 17:27 :08
========================================
-% is pressed                          
13-AUG-23 17:27 :08
========================================
-% is pressed                          
13-AUG-23 17:27 :08
========================================
  WORLD coordinate(G:1)                
13-AUG-23 17:27 :02
========================================
COORD is pressed                       
13-AUG-23 17:27 :02
========================================
  JGFRM coordinate(G:1)                
13-AUG-23 17:27 :02
========================================
COORD is pressed                       
13-AUG-23 17:27 :02
========================================
  JOINT coordinate(G:1)                
13-AUG-23 17:27 :00
========================================
COORD is pressed                       
13-AUG-23 17:27 :00
========================================
   PATH coordinate(G:1)                
13-AUG-23 17:27 :00
========================================
COORD is pressed                       
13-AUG-23 17:27 :00
========================================
   USER coordinate(G:1)                
13-AUG-23 17:26 :28
========================================
COORD is pressed                       
13-AUG-23 17:26 :28
========================================
   TOOL coordinate(G:1)                
13-AUG-23 17:26 :26
========================================
COORD is pressed                       
13-AUG-23 17:26 :26
========================================
  WORLD coordinate(G:1)                
13-AUG-23 17:26 :26
========================================
COORD is pressed                       
13-AUG-23 17:26 :26
========================================
  JGFRM coordinate(G:1)                
13-AUG-23 17:26 :26
========================================
COORD is pressed                       
13-AUG-23 17:26 :26
========================================
  JOINT coordinate(G:1)                
13-AUG-23 17:26 :24
========================================
COORD is pressed                       
13-AUG-23 17:26 :24
========================================
   PATH coordinate(G:1)                
13-AUG-23 17:26 :22
========================================
COORD is pressed                       
13-AUG-23 17:26 :22
========================================
   USER coordinate(G:1)                
13-AUG-23 17:26 :22
========================================
COORD is pressed                       
13-AUG-23 17:26 :22
========================================
   TOOL coordinate(G:1)                
13-AUG-23 17:26 :20
========================================
COORD is pressed                       
13-AUG-23 17:26 :20
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:25 :24
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :18
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :18
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :18
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :18
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :18
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :16
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :16
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :14
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :06
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:25 :02
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
Override 1%                            
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
Override 2%                            
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
Override 3%                            
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
Override 4%                            
13-AUG-23 17:25 :00
========================================
-% is pressed                          
13-AUG-23 17:25 :00
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:24 :58
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:24 :56
========================================
Override 5%                            
13-AUG-23 17:24 :46
========================================
SHIFT +% is pressed                    
13-AUG-23 17:24 :46
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:24 :44
========================================
Override 1%                            
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 2%                            
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 3%                            
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 4%                            
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 5%                            
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 10%                           
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 15%                           
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
Override 20%                           
13-AUG-23 17:24 :44
========================================
-% is pressed                          
13-AUG-23 17:24 :44
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:24 :38
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:24 :34
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:24 :30
========================================
PREV is pressed                        
13-AUG-23 17:24 :24
========================================
PREV is pressed                        
13-AUG-23 17:24 :22
========================================
PREV is pressed                        
13-AUG-23 17:24 :22
========================================
PREV is pressed                        
13-AUG-23 17:24 :22
========================================
Override 25%                           
13-AUG-23 17:23 :24
========================================
SHIFT +% is pressed                    
13-AUG-23 17:23 :24
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:23 :14
========================================
Override 5%                            
13-AUG-23 17:23 :10
========================================
SHIFT -% is pressed                    
13-AUG-23 17:23 :10
========================================
Override 25%                           
13-AUG-23 17:23 :10
========================================
SHIFT -% is pressed                    
13-AUG-23 17:23 :10
========================================
Override 50%                           
13-AUG-23 17:23 :10
========================================
SHIFT -% is pressed                    
13-AUG-23 17:23 :10
========================================
Override 100%                          
13-AUG-23 17:23 :08
========================================
SHIFT +% is pressed                    
13-AUG-23 17:23 :08
========================================
Override 50%                           
13-AUG-23 17:23 :08
========================================
SHIFT +% is pressed                    
13-AUG-23 17:23 :08
========================================
Override 25%                           
13-AUG-23 17:23 :08
========================================
SHIFT +% is pressed                    
13-AUG-23 17:23 :08
========================================
Override 5%                            
13-AUG-23 17:23 :08
========================================
SHIFT +% is pressed                    
13-AUG-23 17:23 :08
========================================
SHIFT,-X(J1) is pressed                
13-AUG-23 17:23 :06
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:20 :52
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:20 :50
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:20 :42
========================================
SHIFT,-X(J1) is pressed                
13-AUG-23 17:20 :26
========================================
SHIFT,-Y(J2) is pressed                
13-AUG-23 17:19 :24
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:19 :16
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:19 :12
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:19 :10
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:19 :04
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:18 :58
========================================
SHIFT,-X(J1) is pressed                
13-AUG-23 17:18 :56
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:18 :52
========================================
+% is pressed                          
13-AUG-23 17:18 :44
========================================
+% is pressed                          
13-AUG-23 17:18 :44
========================================
-% is pressed                          
13-AUG-23 17:18 :42
========================================
-% is pressed                          
13-AUG-23 17:18 :42
========================================
-% is pressed                          
13-AUG-23 17:18 :42
========================================
Override 1%                            
13-AUG-23 17:18 :42
========================================
-% is pressed                          
13-AUG-23 17:18 :42
========================================
SHIFT,+Y(J2) is pressed                
13-AUG-23 17:18 :32
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:18 :22
========================================
Override 2%                            
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
Override 3%                            
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
Override 4%                            
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
Override 5%                            
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
Override 10%                           
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
Override 15%                           
13-AUG-23 17:18 :20
========================================
-% is pressed                          
13-AUG-23 17:18 :20
========================================
SHIFT,+Z(J3) is pressed                
13-AUG-23 17:18 :02
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:18 :00
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:17 :54
========================================
SHIFT,-Z(J3) is pressed                
13-AUG-23 17:17 :52
========================================
SHIFT,+X(J1) is pressed                
13-AUG-23 17:17 :48
========================================
R E S E T                              
                                       
                              00000000 
13-AUG-23 17:17 :44
========================================
FILE 'ZDLOG.DG' is saved               
13-AUG-23 17:17 :44
========================================
FILE 'WVSETUP.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'WVSCHED.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'VTRNDIAG.LS' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'VIMGDIAG.ZIP' is saved           
13-AUG-23 17:17 :44
========================================
FILE 'VDEVDIAG.DAT' is saved           
13-AUG-23 17:17 :44
========================================
FILE 'VCMRINIT.VR' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'VARCHG.XML' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'UPDTLOG.LS' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'UPDATES.DAT' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'TPEINS.XML' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'TPACCN.DG' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'SYSVARS.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SYSUIF.SV' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'SYSSERVO.SV' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SYSPASS.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SYSMAST.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SYSMACRO.SV' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SYSHOST.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SYSFSAC.SV' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SYSFRAME.SV' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SWIUPDT.VR' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'SUMMARY.DG' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'STRREG.VR' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'SHADOW.DG' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'SENDSYSV.TP' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SENDEVNT.TP' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SENDDATA.TP' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'SECLOG.DG' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'REQMENU.TP' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'RCMSGLIB.DG' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'RCMERR.DG' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'RCMCFG.XML' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'PSRBWLD.CM' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'POSREG.VR' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'ORDERFIL.DAT' is saved           
13-AUG-23 17:17 :44
========================================
FILE 'NUMREG.VR' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'NOTIFY.DG' is saved              
13-AUG-23 17:17 :44
========================================
FILE 'MTPARAM.VR' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'MIXLOGIC.SV' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'MEMCHECK.DG' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'LR2D.DT' is saved                
13-AUG-23 17:17 :44
========================================
FILE 'LOGBOOK.LS' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'LAB_WELD_1.TP' is saved          
13-AUG-23 17:17 :44
========================================
FILE 'IRC_STLABEL.VR' is saved         
13-AUG-23 17:17 :44
========================================
FILE 'IRC_STATUS.VR' is saved          
13-AUG-23 17:17 :44
========================================
FILE 'IRC_MSG.VR' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'IRC_COUNTER.VR' is saved         
13-AUG-23 17:17 :44
========================================
FILE 'IPKDMP.ZIP' is saved             
13-AUG-23 17:17 :44
========================================
FILE 'IOSTATUS.CM' is saved            
13-AUG-23 17:17 :44
========================================
FILE 'HTTPKCL.VR' is saved             
13-AUG-23 17:17 :42
========================================
FILE 'HIST.LS' is saved                
13-AUG-23 17:17 :42
========================================
FILE 'GIGELOG.DG' is saved             
13-AUG-23 17:17 :42
========================================
FILE 'GETDATA.TP' is saved             
13-AUG-23 17:17 :42
========================================
FILE 'GEMDATA.VR' is saved             
13-AUG-23 17:17 :42
========================================
FILE 'FTPLOG.DG' is saved              
13-AUG-23 17:17 :42
========================================
FILE 'FRAMEVAR.VR' is saved            
13-AUG-23 17:17 :42
========================================
FILE 'FLEXUIF.XML' is saved            
13-AUG-23 17:17 :42
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
I/O              
========================================
 SO[    3]    ON  -> OFF
Tick:   269822
TB:     -1387217610
16-AUG-23 12:43 :48
========================================
 UO[    2]    OFF -> ON 
 UO[    6]    ON  -> OFF
Tick:   269821
TB:     -1387227284
16-AUG-23 12:43 :48
========================================
 SO[    3]    OFF -> ON 
Tick:   262304
TB:     -1462947173
16-AUG-23 12:43 :42
========================================
 UO[    2]    ON  -> OFF
 UO[    6]    OFF -> ON 
Tick:   262303
TB:     -1462952656
16-AUG-23 12:43 :42
========================================
 SO[    7]    OFF -> ON 
Tick:   262269
TB:     -1463575297
16-AUG-23 12:43 :42
========================================
 UO[    8]    OFF -> ON 
Tick:   262268
TB:     -1463575653
16-AUG-23 12:43 :42
========================================
 SO[    3]    ON  -> OFF
Tick:   4060
TB:     236871087
16-AUG-23 12:39 :22
========================================
 UO[    6]    ON  -> OFF
Tick:   4059
TB:     236864315
16-AUG-23 12:39 :22
========================================
 UO[    2]    OFF -> ON 
Tick:   1056
TB:     204652894
16-AUG-23 12:39 :18
========================================
 UO[    6]    OFF -> ON 
Tick:   1042
TB:     196258918
16-AUG-23 12:39 :18
========================================
 SO[    3]    OFF -> ON 
Tick:   1022
TB:     195483006
16-AUG-23 12:39 :18
========================================
 WO[    9]    OFF
 WO[   10]    OFF
 WO[   11]    OFF
 WO[   12]    OFF
 WO[   13]    OFF
 WO[   14]    OFF
 WO[   15]    OFF
 WO[   16]    OFF
 WO[   17]    OFF
 WO[   18]    OFF
 WO[   19]    OFF
 WO[   20]    OFF
 WO[   21]    OFF
 WO[   22]    OFF
 WO[   23]    OFF
 WO[   24]    OFF
 UI[    1]    ON 
 UI[    2]    ON 
 UI[    3]    ON 
 UI[    4]    OFF
 UI[    5]    OFF
 UI[    6]    OFF
 UI[    7]    OFF
 UI[    8]    ON 
 UI[   17]    OFF
 UI[   18]    OFF
 UI[   19]    OFF
 UI[   20]    OFF
 UI[   21]    OFF
 UI[   22]    OFF
 UI[   23]    OFF
 UI[   24]    OFF
 UI[   33]    OFF
 UI[   34]    OFF
 UO[    1]    OFF
 UO[    2]    OFF
 UO[    3]    OFF
 UO[    4]    OFF
 UO[    5]    OFF
 UO[    6]    OFF
 UO[    7]    OFF
 UO[    8]    OFF
 UO[   17]    OFF
 UO[   18]    OFF
 UO[   19]    OFF
 UO[   20]    OFF
 UO[   21]    OFF
 UO[   22]    OFF
 UO[   23]    OFF
 UO[   24]    OFF
 UO[   33]    OFF
 UO[   34]    OFF
 UO[   35]    OFF
 UO[   36]    OFF
WSI[    1]    OFF
WSI[    9]    OFF
WSI[   17]    OFF
WSO[    1]    OFF
WSO[    9]    OFF
WSO[   17]    OFF
Tick:   1014
TB:     195468080
16-AUG-23 12:39 :18
========================================
 AO[    1]    0
 AO[    3]    0
 AO[    3]    0
 AO[    5]    0
 AO[    5]    0
 AO[    7]    0
 WI[    1]    OFF
 WI[    2]    OFF
 WI[    3]    OFF
 WI[    4]    OFF
 WI[    5]    OFF
 WI[    6]    OFF
 WI[    7]    OFF
 WI[    8]    OFF
 WI[    9]    OFF
 WI[   10]    OFF
 WI[   11]    OFF
 WI[   12]    OFF
 WI[   13]    OFF
 WI[   14]    OFF
 WI[   15]    OFF
 WI[   16]    OFF
 WI[   17]    OFF
 WI[   18]    OFF
 WI[   19]    OFF
 WI[   20]    OFF
 WI[   21]    OFF
 WI[   22]    OFF
 WI[   23]    OFF
 WI[   24]    OFF
 WO[    1]    OFF
 WO[    2]    OFF
 WO[    3]    OFF
 WO[    4]    OFF
 WO[    5]    OFF
 WO[    6]    OFF
 WO[    7]    OFF
 WO[    8]    OFF
Tick:   1013
TB:     195467509
16-AUG-23 12:39 :18
========================================
 AI[   15]    0
 AI[   17]    0
 AI[   13]    0
 AI[   15]    0
 AI[   17]    0
 AI[   19]    0
 AI[   21]    0
 AI[   23]    0
Tick:   1012
TB:     195466298
16-AUG-23 12:39 :18
========================================
 AI[    5]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[    7]    0
 AI[    9]    0
 AI[   11]    0
 AI[   13]    0
Tick:   1011
TB:     194814127
16-AUG-23 12:39 :18
========================================
 DO[   49]    OFF
 DO[   50]    OFF
 DO[   51]    OFF
 DO[   52]    OFF
 DO[   53]    OFF
 DO[   54]    OFF
 DO[   55]    OFF
 DO[   56]    OFF
 DO[   57]    OFF
 DO[   58]    OFF
 DO[   59]    OFF
 DO[   60]    OFF
 DO[   61]    OFF
 DO[   62]    OFF
 DO[   63]    OFF
 DO[   64]    OFF
 DO[   65]    OFF
 DO[   66]    OFF
 DO[   67]    OFF
 DO[   68]    OFF
 DO[   69]    OFF
 DO[   70]    OFF
 DO[   71]    OFF
 DO[   72]    OFF
 DO[   73]    OFF
 DO[   74]    OFF
 DO[   75]    OFF
 DO[   76]    OFF
 DO[   77]    OFF
 DO[   78]    OFF
 DO[   79]    OFF
 DO[   80]    OFF
 DO[   81]    OFF
 DO[   82]    OFF
 DO[   83]    OFF
 DO[   84]    OFF
 DO[   85]    OFF
 DO[   86]    OFF
 DO[   87]    OFF
 DO[   88]    OFF
 DO[   89]    OFF
 DO[   90]    OFF
 DO[   91]    OFF
 DO[   92]    OFF
 DO[   93]    OFF
 DO[   94]    OFF
 DO[   95]    OFF
 DO[   96]    OFF
 DO[   97]    OFF
 DO[   98]    OFF
 DO[   99]    OFF
 DO[  100]    OFF
 DO[  101]    OFF
 DO[  102]    OFF
 DO[  103]    OFF
 DO[  104]    OFF
 DO[  105]    OFF
 DO[  106]    OFF
 DO[  107]    OFF
 DO[  108]    OFF
 DO[  109]    OFF
 DO[  110]    OFF
 DO[  111]    OFF
 DO[  112]    OFF
 DO[  113]    OFF
 DO[  114]    OFF
 DO[  115]    OFF
 DO[  116]    OFF
 DO[  117]    OFF
 DO[  118]    OFF
 DO[  119]    OFF
 DO[  120]    OFF
 DO[  121]    OFF
 DO[  122]    OFF
 DO[  123]    OFF
 DO[  124]    OFF
 DO[  125]    OFF
 DO[  126]    OFF
 DO[  127]    OFF
 DO[  128]    OFF
 DO[  129]    OFF
 DO[  130]    OFF
 DO[  131]    OFF
 DO[  132]    OFF
 DO[  133]    OFF
 DO[  134]    OFF
 DO[  135]    OFF
 DO[  136]    OFF
 DO[  137]    OFF
 DO[  138]    OFF
 DO[  139]    OFF
 DO[  140]    OFF
 DO[  141]    OFF
 DO[  142]    OFF
 DO[  143]    OFF
 DO[  144]    OFF
 AI[    1]    0
 AI[    3]    0
Tick:   1010
TB:     194806786
16-AUG-23 12:39 :18
========================================
 DI[   65]    OFF
 DI[   66]    OFF
 DI[   67]    OFF
 DI[   68]    OFF
 DI[   69]    OFF
 DI[   70]    OFF
 DI[   71]    OFF
 DI[   72]    OFF
 DI[   73]    OFF
 DI[   74]    OFF
 DI[   75]    OFF
 DI[   76]    OFF
 DI[   77]    OFF
 DI[   78]    OFF
 DI[   79]    OFF
 DI[   80]    OFF
 DI[   81]    OFF
 DI[   82]    OFF
 DI[   83]    OFF
 DI[   84]    OFF
 DI[   85]    OFF
 DI[   86]    OFF
 DI[   87]    OFF
 DI[   88]    OFF
 DI[   89]    OFF
 DI[   90]    OFF
 DI[   91]    OFF
 DI[   92]    OFF
 DI[   93]    OFF
 DI[   94]    OFF
 DI[   95]    OFF
 DI[   96]    OFF
 DI[   97]    OFF
 DI[   98]    OFF
 DI[   99]    OFF
 DI[  100]    OFF
 DI[  101]    OFF
 DI[  102]    OFF
 DI[  103]    OFF
 DI[  104]    OFF
 DI[  105]    OFF
 DI[  106]    OFF
 DI[  107]    OFF
 DI[  108]    OFF
 DI[  109]    OFF
 DI[  110]    OFF
 DI[  111]    OFF
 DI[  112]    OFF
 DI[  113]    OFF
 DI[  114]    OFF
 DI[  115]    OFF
 DI[  116]    OFF
 DI[  117]    OFF
 DI[  118]    OFF
 DI[  119]    OFF
 DI[  120]    OFF
 DI[  121]    OFF
 DI[  122]    OFF
 DI[  123]    OFF
 DI[  124]    OFF
 DI[  125]    OFF
 DI[  126]    OFF
 DI[  127]    OFF
 DI[  128]    OFF
 DI[  129]    OFF
 DI[  130]    OFF
 DI[  131]    OFF
 DI[  132]    OFF
 DI[  133]    OFF
 DI[  134]    OFF
 DI[  135]    OFF
 DI[  136]    OFF
 DI[  137]    OFF
 DI[  138]    OFF
 DI[  139]    OFF
 DI[  140]    OFF
 DI[  141]    OFF
 DI[  142]    OFF
 DI[  143]    OFF
 DI[  144]    OFF
 DO[   21]    OFF
 DO[   22]    OFF
 DO[   23]    OFF
 DO[   24]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   25]    OFF
 DO[   26]    OFF
 DO[   27]    OFF
 DO[   28]    OFF
 DO[   29]    OFF
 DO[   30]    OFF
 DO[   31]    OFF
 DO[   32]    OFF
 DO[   33]    OFF
 DO[   34]    OFF
 DO[   35]    OFF
 DO[   36]    OFF
 DO[   37]    OFF
 DO[   38]    OFF
 DO[   39]    OFF
 DO[   40]    OFF
 DO[   41]    OFF
 DO[   42]    OFF
 DO[   43]    OFF
 DO[   44]    OFF
 DO[   45]    OFF
 DO[   46]    OFF
 DO[   47]    OFF
 DO[   48]    OFF
Tick:   1009
TB:     194806099
16-AUG-23 12:39 :18
========================================
 SI[    0]    ON 
 SI[    1]    OFF
 SI[    2]    ON 
 SI[    3]    ON 
 SI[    4]    OFF
 SI[    5]    OFF
 SI[    6]    OFF
 SI[    7]    OFF
 SI[    8]    ON 
 SI[    9]    ON 
 SI[   10]    OFF
 SI[   11]    OFF
 SI[   12]    OFF
 SI[   13]    OFF
 SI[   14]    OFF
 SI[   15]    OFF
 SO[    0]    OFF
 SO[    1]    OFF
 SO[    2]    OFF
 SO[    3]    OFF
 SO[    4]    OFF
 SO[    5]    OFF
 SO[    6]    OFF
 SO[    7]    OFF
 SO[    8]    OFF
 SO[    9]    OFF
 SO[   10]    OFF
 SO[   11]    OFF
 SO[   12]    OFF
 SO[   13]    OFF
 SO[   14]    OFF
 SO[   15]    OFF
 RI[    1]    OFF
 RI[    2]    OFF
 RI[    3]    OFF
 RI[    4]    OFF
 RI[    5]    OFF
 RI[    6]    OFF
 RI[    7]    OFF
 RI[    8]    OFF
 RO[    1]    OFF
 RO[    2]    OFF
 RO[    3]    OFF
 RO[    4]    OFF
 RO[    5]    OFF
 RO[    6]    OFF
 RO[    7]    OFF
 RO[    8]    OFF
SSI[    1]    OFF
SSI[    2]    OFF
SSI[    3]    OFF
SSI[    4]    OFF
SSI[    5]    OFF
SSI[    6]    OFF
SSI[    7]    OFF
SSI[    8]    OFF
SSI[    9]    OFF
SSI[   10]    OFF
SSI[   11]    OFF
SSI[   12]    OFF
SSI[   13]    OFF
SSI[   14]    OFF
 DI[   19]    OFF
 DI[   20]    OFF
 DI[   21]    OFF
 DI[   22]    OFF
 DI[   23]    OFF
 DI[   24]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   25]    OFF
 DI[   26]    OFF
 DI[   27]    OFF
 DI[   28]    OFF
 DI[   29]    OFF
 DI[   30]    OFF
 DI[   31]    OFF
 DI[   32]    OFF
 DI[   33]    OFF
 DI[   34]    OFF
 DI[   35]    OFF
 DI[   36]    OFF
 DI[   37]    OFF
 DI[   38]    OFF
 DI[   39]    OFF
 DI[   40]    OFF
 DI[   41]    OFF
 DI[   42]    OFF
 DI[   43]    OFF
 DI[   44]    OFF
 DI[   45]    OFF
 DI[   46]    OFF
 DI[   47]    OFF
 DI[   48]    OFF
 DI[   49]    OFF
 DI[   50]    OFF
 DI[   51]    OFF
 DI[   52]    OFF
 DI[   53]    OFF
 DI[   54]    OFF
 DI[   55]    OFF
 DI[   56]    OFF
 DI[   57]    OFF
 DI[   58]    OFF
 DI[   59]    OFF
 DI[   60]    OFF
 DI[   61]    OFF
 DI[   62]    OFF
 DI[   63]    OFF
 DI[   64]    OFF
Tick:   1008
TB:     194804772
16-AUG-23 12:39 :18
