ERRAPP.LS      Robot Name ROBOT 13-AUG-23 17:37:44  

1" 13-AUG-23 17:36:56 " ARC -121 Weld not performed(Sim mode)             " " WARN                          00000000" 
2" 13-AUG-23 16:17:28 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
3" 13-AUG-23 15:19:38 " APSH-155 HOME position not recorded               " APSH-156 Specify Home in Ref Pos Menu             " WARN                          00000000" 
